---
title: "1.0_francesco_juan_analisis_data_exploratorio"
output: html_document
date: '2022-10-04'
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

#read Data

```{r}
library(readr)
library(readxl)
library(dplyr)
library(skimr)
library(dlookr) 
library(inspectdf) 
library(stringr)
library(ggplot2)
library(caret)
library(ggiraphExtra)
library(rcompanion)
library(naniar)
library(showtext)

#Leer data
original_df <- read_delim("../data/raw/Data para R.csv", 
                          ";", escape_double = FALSE, locale = locale(decimal_mark = ","), 
                          trim_ws = TRUE)

View(original_df)
```

#recodificacion de datos

```{r}
original_df$sexo <- as.factor(original_df$sexo)
original_df$municipio <- as.factor(original_df$municipio)
original_df$trabajo_actual <- as.factor(original_df$trabajo_actual)
original_df$educación <- as.factor(original_df$educación)
original_df$tipo_universidad <- as.factor(original_df$tipo_universidad)
original_df$tipo_dispositivo_rrss <- as.factor(original_df$tipo_dispositivo_rrss)
original_df$top1_rrss <- as.factor(original_df$top1_rrss)
original_df$top2_rrss <- as.factor(original_df$top2_rrss)
original_df$top3_rrss <- as.factor(original_df$top3_rrss)
original_df$top4_rrss <- as.factor(original_df$top4_rrss)
original_df$top5_rrss <- as.factor(original_df$top5_rrss)
original_df$internet_fijo <- as.factor(original_df$internet_fijo)
original_df$calidad_internet_fijo <- as.factor(original_df$calidad_internet_fijo)
original_df$fallas_servicio <- as.factor(original_df$fallas_servicio)
original_df$internet_fijo_positivo <- as.factor(original_df$internet_fijo_positivo)
original_df$internet_fijo_negativo <- as.factor(original_df$internet_fijo_negativo)
original_df$fallo_internet_reestablecimiento <- as.factor(original_df$fallo_internet_reestablecimiento)
original_df$tipo_empresa_internet_fijo <- as.factor(original_df$tipo_empresa_internet_fijo)
original_df$cambio_proveedor_reciente <- as.factor(original_df$cambio_proveedor_reciente)
original_df$medida_secundaria_fallo_internet_fijo <- as.factor(original_df$medida_secundaria_fallo_internet_fijo)
original_df$pago_internet_dolares <- as.factor(original_df$pago_internet_dolares)
original_df$acceso_celular_rrss <- as.factor(original_df$acceso_celular_rrss)
original_df$calidad_navegacion_movil <- as.factor(original_df$calidad_navegacion_movil)
original_df$navegacion_movil_positivo <- as.factor(original_df$navegacion_movil_positivo)
original_df$navegacion_movil_negativo <- as.factor(original_df$navegacion_movil_negativo)
```

#total encuestados y porcentajes

```{r}

  muestra <- 423

  #Variable de exclusion 1: edad 18-25
  muestra_edad <- 394
  porcentaje_exclu1 <- ((muestra - muestra_edad)/muestra)*100 
  porcentaje_exclu1

  #Variable de exclusion 2: estudiando
  muestra_carrera <- 354
  porcentaje_exclu2 <- ((muestra_edad - muestra_carrera)/muestra_edad)*100
  porcentaje_exclu2

  #Variable de exclusion 3: residencia Municipios
  muestra_mun <- 334
  porcentaje_exclu3 <- ((muestra_carrera - muestra_mun)/muestra_carrera)*100
  porcentaje_exclu3

  #Variable de exclusion 4: diagnostico clinico
  muestra_dx <- 261
  porcentaje_exclu4 <- ((muestra_mun - muestra_dx)/muestra_mun)*100
  porcentaje_exclu4

```

```{r}

```
